CREATE TABLE tblSuperAdmin
(
    SuperAdminId INT PRIMARY KEY IDENTITY(1,1),
    UserName VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Email_Id VARCHAR(150) NOT NULL UNIQUE,
    PhoneNumber VARCHAR(20) NULL,
    LastLogin DATETIME NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedAt DATETIME NOT NULL DEFAULT(GETDATE())
);