EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 1,  @PaymentMode = 'Cash';
EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 2,  @PaymentMode = 'UPI';
EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 3,  @PaymentMode = 'Bank Transfer';
EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 4,  @PaymentMode = 'Cash';
EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 5,  @PaymentMode = 'UPI';
EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 6,  @PaymentMode = 'Bank Transfer';
EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 7,  @PaymentMode = 'Cash';
EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 8,  @PaymentMode = 'UPI';
EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 9,  @PaymentMode = 'Bank Transfer';
EXEC spPaySalaryToEmployeeByEmployeeIdAndPaymentMethod @EmployeeId = 10, @PaymentMode = 'Cash';